### ISSUE TITLE
tries conda env build even for singularity runs

### ISSUE THREAD

**Issue by kubranarci** [ghga-de/nf-platypusindelcalling#32]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

Conda env seems to be tried to be build even for singularity runs for nf-core modules:

happens in vep and bcftools

### Command used and terminal output

```console
#!/bin/bash
module load nextflow/22.07.1-edge
nextflow run main.nf -profile dkfz_cluster_38,singularity --input testdata/samplesheet_test.csv -resume --annotation_tool vep
```

### Relevant files

![image (2)](https://github.com/ghga-de/nf-platypusindelcalling/assets/25736789/bd41e84a-dbae-42f8-8f54-4a0bd9dbbba3)
![image (1)](https://github.com/ghga-de/nf-platypusindelcalling/assets/25736789/d3bdb0ed-0093-4f0a-a30f-6454e2d2c5b1)
![image](https://github.com/ghga-de/nf-platypusindelcalling/assets/25736789/011abc4e-4fbc-42af-b96b-9ef3ea28cc40)

**Comment by NagaComBio** [comment]
The code snippet below shows a modification made to the `modules/nf-core/modules/ensemblvep/vep/main.nf` file. The change skips the creation of the conda environment and moves directly to the singularity environment when the `enable_conda` option is set to `false` (which is the default setting). The code uses a ternary operator to explicitly check for the `enable_conda` option. Without this operator, it is unclear how the nf-core modules would recognize the `enable_conda` option. 

```
//conda "${moduleDir}/environment.yml"
(params.enable_conda ? "${moduleDir}/environment.yml" : null)
```

**Comment by kubranarci** [comment]
Thank you @NagaComBio  to recognize this! perfect. I am implementing the solution into https://github.com/ghga-de/nf-platypusindelcalling/pull/31
